### ISSUE TITLE
Feature request: allow specifying environment variables in YAML schema

### ISSUE THREAD

**Issue by nre-ableton** [wickedchicken/checklist#75]
I have some projects for which I would like run commands which require an associated Python virtualenv. I could run `checklist` from within the virtualenv, but I sometimes run git commands from a separate shell (or IDE) which isn't always aware of the IDE.

It turns out that assuming the virtualenv is already properly configured, you can just run the executables there directly. However, I sometimes run into path issues when some of the tests want to call executables from other pip modules.

Basically, what I'd like to do is be able to specify environment variables which would be passed to each automated test. I imagine this could look something like this:

```yaml
---
schema_version: 2
environment:
  VENV_BIN: "$HOME/caches/venv/my_project/bin"
  PATH: "$PATH:$VENV_BIN"
committing:
  automated:
    - python ./run.py check  # assumes $PATH is correct 
```

I'm not sure if the `PATH` definition above would work as expected unless the variables were expanded in the shell.
